const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),sharp=require('sharp'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
async function main(){
 const pack=JSON.parse(await fs.readFile(path.join(root,'manifest.json'),'utf8')),{LoungeSession,transferItem,resolveSpriteFrame}=await import(pathToFileURL(path.join(root,'tools/lounge-runtime.mjs')));
 let frames=0,clips=0;assert.equal(pack.characterCount,7);const details=[];
 for(const c of pack.characters){
  const atlas=JSON.parse(await fs.readFile(path.join(root,c.atlas),'utf8')),meta=await sharp(path.join(root,c.image)).metadata();assert.equal(meta.width,1280);assert.equal(meta.height,3680);assert.equal(Object.keys(atlas.frames).length,177);const hashes={},atlasPixels=await sharp(path.join(root,c.image)).ensureAlpha().raw().toBuffer();
  for(const key of Object.keys(atlas.frames)){
   const file=path.join(root,'characters',c.id,'frames',key+'.png'),{data,info}=await sharp(file).ensureAlpha().raw().toBuffer({resolveWithObject:true});assert.equal(info.width,160);assert.equal(info.height,160);let solid=0;
   for(let y=0;y<160;y++)for(let x=0;x<160;x++){const a=data[(y*160+x)*4+3];if(a>96)solid++;if(x<2||x>157||y<2||y>157)assert.equal(a,0,c.id+'/'+key+': edge');}
   const tile=atlas.frames[key].frame;for(let y=0;y<160;y++)assert.deepEqual(atlasPixels.subarray(((tile.y+y)*1280+tile.x)*4,((tile.y+y)*1280+tile.x+160)*4),data.subarray(y*160*4,(y+1)*160*4),c.id+'/'+key+': atlas differs from exported PNG');
   assert.ok(solid>350);hashes[key]=crypto.createHash('sha256').update(data).digest('hex');frames++;
  }
  assert.equal(Object.keys(c.animations).length,50);
  for(const [name,cl]of Object.entries(c.animations)){
   assert.equal(cl.frames.length,8);assert.equal(cl.durationsMs.length,8);assert.equal(cl.totalDurationMs,cl.durationsMs.reduce((a,b)=>a+b,0));assert.ok(cl.durationsMs.every(v=>v>0));
   for(let i=0;i<8;i++){const fr=resolveSpriteFrame(cl,i);assert.ok(atlas.frames[fr.frame]);assert.equal(typeof fr.flipX,'boolean');}
   if(cl.completionAction&&!cl.completionAction.startsWith('base:'))assert.ok(c.animations[cl.completionAction],name+': invalid next action');
   assert.ok(new Set(cl.frames.map(k=>hashes[k])).size>1,name+': no animation');for(const e of cl.events)assert.ok(e.frame>=0&&e.frame<8);clips++;
  }
  for(const kind of ['sofa','armchair']){
   assert.equal(hashes[kind+'_sit_right_07'],hashes[kind+'_idle_right_00']);assert.equal(hashes[kind+'_drink_right_00'],hashes[kind+'_idle_right_00']);assert.equal(hashes[kind+'_drink_right_07'],hashes[kind+'_idle_right_00']);
   for(const action of ['talk','laugh','game_win']){const endpoint=hashes[kind+(action==='game_win'?'_game':'_idle')+'_right_00'];assert.equal(hashes[kind+'_'+action+'_right_00'],endpoint);assert.equal(hashes[kind+'_'+action+'_right_07'],endpoint);}
   assert.deepEqual(c.animations[kind+'_stand_right'].frames,[...c.animations[kind+'_sit_right'].frames].reverse());
   assert.equal(resolveSpriteFrame(c.animations[kind+'_sit_left'],0).frame,'standing_left');assert.equal(resolveSpriteFrame(c.animations[kind+'_sit_left'],0).flipX,false);
  }
  assert.notEqual(hashes.sofa_idle_right_00,hashes.armchair_idle_right_00,'Sofa and armchair poses must differ');
  for(const direction of ['right','left']){const actual=await sharp(path.join(root,'characters',c.id,'frames',direction==='right'?'sofa_sit_right_00.png':'standing_left.png')).extract({left:16,top:24,width:128,height:128}).raw().toBuffer(),original=await sharp(path.join(root,'../06_CHARACTER_ANIMATIONS/characters',c.id,'frames','idle_'+direction+'_00.png')).raw().toBuffer();assert.deepEqual(actual,original);}
  details.push({id:c.id,frames:177,clips:50,distinctFurniturePoses:true});
 }
 assert.equal(frames,1239);assert.equal(clips,350);
 const s=new LoungeSession;assert.equal(s.reserveStorage('A'),true);assert.equal(s.reserveStorage('B'),false);assert.equal(s.pickup('A','early'),false);assert.equal(s.openDrawer('A'),true);assert.equal(s.pickup('B','steal'),false);assert.equal(s.pickup('A','pick'),true);assert.equal(s.pickup('A','pick'),false);assert.equal(s.consoleLocation,'carried');s.closeDrawer('A');assert.equal(s.install('B','wrong-install'),false);assert.equal(s.install('A','install'),true);
 assert.equal(s.reserveSeat('A','sofa'),true);assert.equal(s.reserveSeat('A','armchair'),false);assert.equal(s.reserveSeat('B','sofa'),false);assert.equal(s.reserveSeat('B','armchair'),true);assert.equal(s.join('A','sofa'),false);s.markSeated('A','sofa');s.markSeated('B','armchair');assert.equal(s.join('A','sofa'),true);assert.equal(s.join('B','armchair'),true);assert.equal(new Set(s.players.values()).size,2);
 s.reserveSeat('C','spare');s.markSeated('C','spare');assert.equal(s.join('C','spare'),false);assert.equal(s.takeInstalled('C','midgame'),false);assert.equal(s.releaseSeat('A','sofa'),false);s.pause();assert.equal(s.screen,'paused');s.resume();assert.equal(s.screen,'playing');s.leave('A');s.leave('B');s.markStanding('A');s.markStanding('B');assert.equal(s.releaseSeat('A','sofa'),true);assert.equal(s.releaseSeat('B','armchair'),true);
 assert.equal(s.takeInstalled('A','take'),true);s.openDrawer('A');assert.equal(s.store('A','store'),true);assert.equal(s.store('A','store'),false);s.closeDrawer('A');assert.equal(s.consoleLocation,'drawer');assert.equal(s.cabinetState,0);
 s.openDrawer('A');s.pickup('A','second-pick');s.removeActor('A');assert.equal(s.consoleLocation,'recovery');assert.equal(s.carrier,null);assert.equal(s.recoverConsole('B','recover'),true);s.openDrawer('B');assert.equal(s.store('B','recovered-store'),true);
 const inv={items:new Map([['parcel','A']]),transactions:new Set};assert.equal(transferItem(inv,'parcel','A','B','x'),true);assert.equal(transferItem(inv,'parcel','A','B','x'),false);assert.equal(transferItem(inv,'parcel','A','C','y'),false);assert.equal(inv.items.get('parcel'),'B');assert.equal(inv.items.size,1);
 const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1440,height:1180},deviceScaleFactor:1}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.join(root,'index.html'));await page.waitForFunction(()=>LOUNGE_DEMO?.ready);await page.evaluate(()=>LOUNGE_DEMO.setPaused(true));assert.equal(await page.locator('#character option').count(),7);assert.equal(await page.locator('[data-action]').count(),50);
 for(const action of Object.keys(pack.characters[0].animations)){await page.locator('[data-action="'+action+'"]').click();await page.evaluate(()=>LOUNGE_DEMO.advance(400));}
 for(const [mode,time]of [['sit',2300],['drink',2200],['talk',600],['laugh',650],['win',650],['game',1800],['pat',490],['exchange',700]]){await page.locator('button[data-mode="'+mode+'"]').click();await page.evaluate(t=>LOUNGE_DEMO.advance(t),time);await page.screenshot({path:path.join(root,'previews',mode+'.png'),fullPage:true});}
 await page.locator('button[data-mode=setup]').click();for(let i=0;i<95;i++)await page.evaluate(()=>LOUNGE_DEMO.advance(100));assert.equal(await page.evaluate(()=>LOUNGE_DEMO.session.consoleLocation),'installed');assert.equal(await page.evaluate(()=>LOUNGE_DEMO.session.players.size),2);await page.screenshot({path:path.join(root,'previews/setup-complete.png'),fullPage:true});
 await page.locator('button[data-mode=return]').click();for(let i=0;i<80;i++)await page.evaluate(()=>LOUNGE_DEMO.advance(100));assert.equal(await page.evaluate(()=>LOUNGE_DEMO.session.consoleLocation),'drawer');assert.equal(await page.evaluate(()=>LOUNGE_DEMO.session.drawerOpen),false);
 for(let i=0;i<115;i++)await page.evaluate(()=>LOUNGE_DEMO.advance(100));assert.equal(await page.evaluate(()=>LOUNGE_DEMO.session.consoleLocation),'drawer');
 await page.locator('button[data-mode=exchange]').click();await page.evaluate(()=>LOUNGE_DEMO.advance(600));assert.equal(await page.evaluate(()=>LOUNGE_DEMO.exchangeInventory.items.get('parcel')),await page.locator('#partner').inputValue());assert.equal(await page.evaluate(()=>LOUNGE_DEMO.exchangeInventory.transactions.size),1);
 await page.locator('#character').selectOption('worker_brown_red');await page.locator('#partner').selectOption('worker_blond_blue');await page.locator('button[data-mode=game]').click();await page.screenshot({path:path.join(root,'previews/game-other-characters.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(root,'previews/mobile.png'),fullPage:false});assert.deepEqual(errors,[]);await browser.close();
 const report={frameCount:frames,clipCount:clips,characters:details,checks:['RGBA transparency and safe margins','All frame/atlas references, pixel-exact atlas tiles and timings','Nonstatic clips','Different sofa and armchair body poses','Exact sit/drink/talk/laugh/win canonical endpoint packing','Original left/right standing pose preserved in 160px cell','Per-frame mirror overrides','Seat exclusivity and posture gate before gaming','One console and at most two allocated controllers','Storage mutex, event idempotency and recovery on removal','Single-owner atomic parcel exchange','Offline preview, all50 actions, other character pair and mobile','Complete retrieve/install/play/return demo lifecycle'],limitations:['No target game application is present: integrate with its navigation, collisions and task events.','Left clips use mirrored authored right art plus canonical standing overrides.','New lounge clips provide lateral directions; vertical carrying requires additional art or a carefully staged direction in the target scene.','Seat/cabinet/partner offsets are initial placements for this office; calibrate collisions and foreground furniture masks in the game.']};await fs.writeFile(path.join(root,'docs/VALIDATION.json'),JSON.stringify(report,null,2));console.log('Verified '+frames+' frames, '+clips+' clips, resources, paired transfer and browser scenarios.');
}
main().catch(e=>{console.error(e);process.exit(1)});
